import type { Feed } from '../types/program';

export const DEFAULT_FEEDS: Feed[] = [
  {
    id: 'nhk-major',
    url: 'https://www.nhk.or.jp/rss/news/cat0.xml',
    title: 'NHK 主要ニュース',
    genre: 'news',
    enabled: true,
  },
];

export const RECOMMENDED_FEEDS: { ja: Feed[]; en: Feed[] } = {
  ja: [
    // ニュース
    {
      id: 'rec-nhk-major',
      url: 'https://www.nhk.or.jp/rss/news/cat0.xml',
      title: 'NHK 主要',
      genre: 'news',
      enabled: true,
    },
    {
      id: 'rec-nhk-social',
      url: 'https://www.nhk.or.jp/rss/news/cat1.xml',
      title: 'NHK 社会',
      genre: 'news',
      enabled: true,
    },
    {
      id: 'rec-nhk-culture',
      url: 'https://www.nhk.or.jp/rss/news/cat2.xml',
      title: 'NHK 文化',
      genre: 'culture',
      enabled: true,
    },
    {
      id: 'rec-nhk-science',
      url: 'https://www.nhk.or.jp/rss/news/cat3.xml',
      title: 'NHK 科学・医療',
      genre: 'science',
      enabled: true,
    },
    {
      id: 'rec-nhk-politics',
      url: 'https://www.nhk.or.jp/rss/news/cat4.xml',
      title: 'NHK 政治',
      genre: 'politics',
      enabled: true,
    },
    {
      id: 'rec-nhk-business',
      url: 'https://www.nhk.or.jp/rss/news/cat5.xml',
      title: 'NHK 経済',
      genre: 'business',
      enabled: true,
    },
    {
      id: 'rec-nhk-world',
      url: 'https://www.nhk.or.jp/rss/news/cat6.xml',
      title: 'NHK 国際',
      genre: 'world',
      enabled: true,
    },
    {
      id: 'rec-nhk-sports',
      url: 'https://www.nhk.or.jp/rss/news/cat7.xml',
      title: 'NHK スポーツ',
      genre: 'sports',
      enabled: true,
    },
    {
      id: 'rec-yahoo-top',
      url: 'https://news.yahoo.co.jp/rss/topics/top-picks.xml',
      title: 'Yahoo!ニュース 主要',
      genre: 'news',
      enabled: true,
    },
    // テック / IT
    {
      id: 'rec-hatena-it',
      url: 'https://b.hatena.ne.jp/hotentry/it.rss',
      title: 'はてブ IT',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-zenn',
      url: 'https://zenn.dev/feed',
      title: 'Zenn',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-qiita-trend',
      url: 'https://qiita.com/popular-items/feed',
      title: 'Qiita トレンド',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-itmedia-news',
      url: 'https://rss.itmedia.co.jp/rss/2.0/news_bursts.xml',
      title: 'ITmedia NEWS',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-gigazine',
      url: 'https://gigazine.net/news/rss_2.0/',
      title: 'GIGAZINE',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-publickey',
      url: 'https://www.publickey1.jp/atom.xml',
      title: 'Publickey',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-impress-internet',
      url: 'https://internet.watch.impress.co.jp/data/rss/1.0/iw/feed.rdf',
      title: 'INTERNET Watch',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-engadget-jp',
      url: 'https://japanese.engadget.com/rss.xml',
      title: 'Engadget 日本版',
      genre: 'tech',
      enabled: true,
    },
    // 総合 / カルチャー
    {
      id: 'rec-hatena-all',
      url: 'https://b.hatena.ne.jp/hotentry.rss',
      title: 'はてブ 総合',
      genre: 'general',
      enabled: true,
    },
    {
      id: 'rec-hatena-life',
      url: 'https://b.hatena.ne.jp/hotentry/life.rss',
      title: 'はてブ 暮らし',
      genre: 'life',
      enabled: true,
    },
    {
      id: 'rec-hatena-fun',
      url: 'https://b.hatena.ne.jp/hotentry/fun.rss',
      title: 'はてブ 世の中',
      genre: 'culture',
      enabled: true,
    },
    // ゲーム / エンタメ
    {
      id: 'rec-hatena-game',
      url: 'https://b.hatena.ne.jp/hotentry/game.rss',
      title: 'はてブ ゲーム・アニメ',
      genre: 'game',
      enabled: true,
    },
  ],
  en: [
    // World / General news
    {
      id: 'rec-bbc-top',
      url: 'https://feeds.bbci.co.uk/news/rss.xml',
      title: 'BBC News',
      genre: 'news',
      enabled: true,
    },
    {
      id: 'rec-bbc-world',
      url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
      title: 'BBC World',
      genre: 'world',
      enabled: true,
    },
    {
      id: 'rec-npr-news',
      url: 'https://feeds.npr.org/1001/rss.xml',
      title: 'NPR News',
      genre: 'news',
      enabled: true,
    },
    {
      id: 'rec-nyt-home',
      url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
      title: 'The New York Times',
      genre: 'news',
      enabled: true,
    },
    {
      id: 'rec-guardian-world',
      url: 'https://www.theguardian.com/world/rss',
      title: 'The Guardian World',
      genre: 'world',
      enabled: true,
    },
    // Business
    {
      id: 'rec-bbc-business',
      url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
      title: 'BBC Business',
      genre: 'business',
      enabled: true,
    },
    {
      id: 'rec-nyt-business',
      url: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
      title: 'NYT Business',
      genre: 'business',
      enabled: true,
    },
    // Tech
    {
      id: 'rec-theverge',
      url: 'https://www.theverge.com/rss/index.xml',
      title: 'The Verge',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-techcrunch',
      url: 'https://techcrunch.com/feed/',
      title: 'TechCrunch',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-arstechnica',
      url: 'https://feeds.arstechnica.com/arstechnica/index',
      title: 'Ars Technica',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-hn-front',
      url: 'https://hnrss.org/frontpage',
      title: 'Hacker News',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-wired',
      url: 'https://www.wired.com/feed/rss',
      title: 'WIRED',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-engadget',
      url: 'https://www.engadget.com/rss.xml',
      title: 'Engadget',
      genre: 'tech',
      enabled: true,
    },
    {
      id: 'rec-bbc-tech',
      url: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
      title: 'BBC Technology',
      genre: 'tech',
      enabled: true,
    },
    // Sports
    {
      id: 'rec-bbc-sport',
      url: 'https://feeds.bbci.co.uk/sport/rss.xml',
      title: 'BBC Sport',
      genre: 'sports',
      enabled: true,
    },
    {
      id: 'rec-espn',
      url: 'https://www.espn.com/espn/rss/news',
      title: 'ESPN',
      genre: 'sports',
      enabled: true,
    },
  ],
};
